# Generated by Django 5.0.7 on 2024-07-27 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loss_type', models.CharField(blank=True, choices=[('during', 'Loss during pregnancy'), ('at or after', 'Loss at birth or shortly after')], max_length=100)),
                ('name', models.CharField(blank=True, help_text='Had you picked out a name or nickname?', max_length=100, null=True)),
                ('parent_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('dob_due_date', models.DateField()),
                ('weight', models.IntegerField(help_text='kilograms')),
                ('image', models.ImageField(default='../default_post_rgq6aq', upload_to='images/')),
                ('memory', models.TextField(blank=True, help_text='Some families find it helpful to write a message directly to their lost loved one, or to share a memory. This should be whatever you will find helpful to your healing journey.', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
