# Generated by Django 5.0.7 on 2024-07-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaf',
            old_name='owner',
            new_name='user',
        ),
    ]
