# Generated by Django 5.0.7 on 2024-07-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_rename_owner_leaf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='dob_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaf',
            name='weight',
            field=models.IntegerField(blank=True, help_text='kilograms', null=True),
        ),
    ]
