# Generated by Django 5.0.7 on 2024-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_alter_leaf_dob_due_date_alter_leaf_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='weight',
            field=models.IntegerField(blank=True, help_text='lbs', null=True),
        ),
    ]
